### ISSUE TITLE
Missing example on how to set configurations per Event

### ISSUE THREAD

**Issue by xucito** [logstash-plugins/logstash-output-java_output_example#6]
How do you configure using Java the ability to have a different configuration per event

i.e. https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html

```
output {
  file {
    path => "/var/log/%{type}.%{+yyyy.MM.dd.HH}"
  }
}
```
In the document it describes pulling and verifying the configurations in the constructor. Is that going to be loaded only on initialization of the worker.

**Comment by danhermann** [comment]
@xucito, making use of event-dependent configuration such as the example above is the responsibility of each plugin that wishes to support it. As an example, you can see how the `java_line` codec supports an event-dependent `format` config setting [here](https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/plugins/codecs/Line.java#L126).

If your plugin has an event-dependent config setting, there is little validation that can be done for the value of that config setting at plugin construction time. The plugin would need to have code to handle situations such as an event that is missing an expected field such as `type` from the example above.

**Comment by xucito** [comment]
Hi @danhermann, thanks for the prompt response. I might be reading this wrong, but **format** is still set and configured as apart of the constructor and is not re-initialized per event? The implementation you link just conditionally allows for the null value of **format**.

An example of what I want to achieve is 
```
output {
  udp {
    "host": <dynamic value that changes per event>
  }
}
```

**Comment by danhermann** [comment]
> Hi @danhermann, thanks for the prompt response. I might be reading this wrong, but **format** is still set and configured as apart of the constructor and is not re-initialized per event? The implementation you link just conditionally allows for the null value of **format**.

You are correct that the `format` setting is not re-initialized per event. It does not need to be re-evaluated because it is applied on a per-event basis to produce an output string that is unique to each event.

> An example of what I want to achieve is
> 
> ```
> output {
>   udp {
>     "host": <dynamic value that changes per event>
>   }
> }
> ```

If I understand correctly, what you are suggesting above is the kind of per-event configuration that is generally not supported in Logstash plugins because it is too expensive. In your example, it's possible that each event could specify a different host which would require the UDP output to open a network connection to a separate host for each event. That would be both resource-intensive and slow.

There is, of course, nothing that would prevent you from writing your own plugin that does do that, but the resource usage and performance would not be good. Depending on what you are trying to achieve (e.g., routing events among a small pool of servers), there are patterns that are commonly used in Logstash to achieve that.

I'm going to close this issue as it's a usage question rather than a bug with the Java plugin API or the example plugin. If you have additional questions, please post in our [Logstash forums](https://discuss.elastic.co/c/logstash). Feel free to tag me there at `@danhermann` and I'll follow up with you there.
